#!/usr/bin/env python3
"""
Batch generate Signal Deep Analysis reports using Playwright.

For each signal CSV that's missing a report in docs/reports/:
  1. Navigate to index.html on localhost
  2. Inject CSV file via input
  3. Click analyze
  4. Extract report HTML
  5. Save as Signal_Deep_Analysis_{sid}.html

Prerequisites:
  - python3 -m http.server 8765 (in docs/ directory)
  - playwright installed
"""
import sys
import os
import time
import glob
from pathlib import Path
from playwright.sync_api import sync_playwright

BASE_DIR = Path(__file__).parent
DOWNLOADS_DIR = BASE_DIR / 'downloads'
REPORTS_DIR = BASE_DIR / 'docs' / 'reports'
SERVER_URL = 'http://localhost:8765/index.html'

def get_all_csvs():
    """Get all signal CSVs mapped by signal ID."""
    csvs = {}
    for f in DOWNLOADS_DIR.glob('forex-forest-signals-page-*.csv'):
        sid = f.stem.replace('forex-forest-signals-page-', '')
        try:
            int(sid)
            csvs[sid] = f
        except ValueError:
            continue
    for f in DOWNLOADS_DIR.glob('[0-9]*.csv'):
        sid = f.stem
        try:
            int(sid)
            if sid not in csvs:
                csvs[sid] = f
        except ValueError:
            continue
    return csvs

def get_existing_deep():
    """Get set of signal IDs with existing deep analysis reports."""
    ids = set()
    for f in REPORTS_DIR.glob('Signal_Deep_Analysis_*.html'):
        sid = f.stem.replace('Signal_Deep_Analysis_', '')
        ids.add(sid)
    return ids

def find_csv_and_sets(sid, csv_map):
    """Find CSV and SET files for a signal ID."""
    csv_path = csv_map.get(sid)
    if not csv_path:
        return None, []
    
    # Find SET files
    set_files = []
    for pattern in [f'signal_{sid}_*.set', f'*{sid}*.set']:
        for sf in DOWNLOADS_DIR.glob(pattern):
            set_files.append(sf)
    
    return csv_path, set_files

def generate_one(page, sid, csv_path, set_files):
    """Generate one deep analysis report."""
    output_path = REPORTS_DIR / f'Signal_Deep_Analysis_{sid}.html'
    
    # Navigate to index.html
    page.goto(SERVER_URL, wait_until='networkidle')
    
    # Set CSV file via input
    page.locator('#csvInput').set_input_files(str(csv_path))
    time.sleep(0.5)
    
    # Set SET files if any
    if set_files:
        page.locator('#setInput').set_input_files([str(sf) for sf in set_files])
        time.sleep(0.5)
    
    # Click analyze
    page.evaluate('()=>document.getElementById("analyzeBtn").click()')
    
    # Poll for results
    for i in range(72):  # 6 min max
        time.sleep(5)
        done = page.evaluate('()=>document.getElementById("results").innerHTML.trim()!==""')
        if done:
            break
    else:
        raise TimeoutError(f'Signal #{sid} analysis timed out')
    
    time.sleep(3)  # Extra time for full render
    
    # Extract report HTML
    report_html = page.evaluate("""() => {
        const style = document.querySelector('style') ? document.querySelector('style').textContent : '';
        const results = document.getElementById('results');
        const version = (typeof APP_VERSION !== 'undefined') ? APP_VERSION : 'TSA';
        return '<!DOCTYPE html><html lang="zh-Hant"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Signal Deep Analysis #' + 
            arguments[0] + '</title><style>' + style + '</style></head><body style="max-width:900px;margin:0 auto;padding:20px;font-family:-apple-system,BlinkMacSystemFont,sans-serif">' +
            results.innerHTML +
            '<footer style="text-align:center;color:#999;padding:20px;font-size:0.85em">Generated by Trade Strategy Analyzer ' + version + '</footer>' +
            '</body></html>';
    }""", sid)
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(report_html)
    
    return output_path.stat().st_size

def main():
    print("=" * 70)
    print("🔍 TSA Deep Analysis Batch Generator")
    print("=" * 70)
    
    # Check server
    import urllib.request
    try:
        urllib.request.urlopen(SERVER_URL, timeout=5)
    except Exception:
        print(f"❌ Server not running at {SERVER_URL}")
        print("   Start it with: cd docs && python3 -m http.server 8765")
        sys.exit(1)
    
    csv_map = get_all_csvs()
    existing = get_existing_deep()
    all_sids = sorted(csv_map.keys(), key=int)
    missing = [s for s in all_sids if s not in existing]
    
    print(f"\n  Total signals: {len(all_sids)}")
    print(f"  Existing reports: {len(existing & set(all_sids))}")
    print(f"  Missing reports: {len(missing)}")
    
    if not missing:
        print("\n✅ All deep analysis reports are up to date!")
        return
    
    print(f"\n  To generate: {', '.join(missing)}")
    print()
    
    success = 0
    fail = 0
    errors = {}
    
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        context = browser.new_context()
        page = context.new_page()
        
        # Collect console errors for debugging
        console_errors = []
        page.on('console', lambda msg: console_errors.append(msg.text) if msg.type == 'error' else None)
        
        for i, sid in enumerate(missing):
            csv_path, set_files = find_csv_and_sets(sid, csv_map)
            if not csv_path:
                print(f"  [{i+1}/{len(missing)}] #{sid}: ❌ No CSV found")
                fail += 1
                errors[sid] = 'No CSV'
                continue
            
            print(f"  [{i+1}/{len(missing)}] #{sid} ({os.path.basename(csv_path)})... ", end="", flush=True)
            console_errors.clear()
            
            try:
                size = generate_one(page, sid, csv_path, set_files)
                print(f"✅ ({size:,} bytes)")
                success += 1
            except Exception as e:
                print(f"❌ {str(e)[:150]}")
                fail += 1
                errors[sid] = str(e)
                # Take screenshot for debugging
                try:
                    page.screenshot(path=f'/tmp/tsa_deep_{sid}.png')
                except:
                    pass
        
        browser.close()
    
    print(f"\n{'='*70}")
    print(f"📊 Deep Analysis Generation Summary")
    print(f"{'='*70}")
    print(f"  ✅ Success: {success}")
    print(f"  ❌ Failed:  {fail}")
    print(f"  Total:     {len(missing)}")
    
    if errors:
        print(f"\n⚠️ Errors:")
        for sid, err in errors.items():
            print(f"  #{sid}: {err[:200]}")
    
    print(f"\n✨ Done! {success} deep analysis reports generated.")

if __name__ == '__main__':
    main()
