#!/usr/bin/env python3
"""
Generate Currency Pair Ranking HTML (DDE v4 — unified theme, matching gh-pages UI).
Reads from the pickle generated by dde_v4_scorer.py.
"""
import pickle
import sys
from pathlib import Path
from collections import defaultdict, Counter
from datetime import datetime

BASE_DIR = Path(__file__).parent
REPORTS_DIR = BASE_DIR / 'reports'
REPORTS_DIR.mkdir(exist_ok=True)

EA_MAP = {
    'DW': ['10437','11984','13790','17547','21698','22200','22278','25830','30359','31781','32719','3291','33101','31593','34574','36338','36397','36511','34259','20846','16538'],
    'SMA': ['106','1980','2351','32278','32541','5001','5275','537','5566','11889','13863','14724','16596','16698','16706','17611','17823','10864','14158','5636'],
    'MKD': ['12962','13461','14341','14592','1470','17962','20805','23617','25668','25260','8325','7919'],
    'S10': ['13798','16596'],
    'Flash': ['19849'],
    'GEM': ['14581'],
    'MAN': ['12173'],
}

EA_COLORS = {
    'DW':    ('#4a148c', '#ce93d8'),
    'SMA':   ('#1b5e20', '#a5d6a7'),
    'MKD':   ('#e65100', '#ffcc80'),
    'Flash': ('#0d47a1', '#90caf9'),
    'S10':   ('#004d40', '#80cbc4'),
    'GEM':   ('#880e4f', '#f48fb1'),
    'MAN':   ('#4527a0', '#b39ddb'),
    'UNK':   ('#333', 'var(--text2)'),
}


def get_ea_style(ea_tag):
    """Get background/color for EA badge. Uses first part of multi-EA tag."""
    first = ea_tag.split('/')[0]
    bg, fg = EA_COLORS.get(first, EA_COLORS['UNK'])
    return f'background:{bg};color:{fg}'


def get_score_class(score):
    if score >= 90: return 's90'
    elif score >= 85: return 's85'
    elif score >= 75: return 's75'
    elif score >= 70: return 's70'
    elif score >= 60: return 's60'
    else: return 's0'


def get_dd_class(dd_value):
    """DD classification — pips-based with $1K context."""
    abs_dd = abs(dd_value)
    if abs_dd < 500:
        return 'dd-g'
    elif abs_dd < 2000:
        return 'dd-y'
    else:
        return 'dd-r'


def get_dd_1k_tier(max_dd_pips, symbol=''):
    """
    $1K account DD tier (King's 6-tier system).
    Converts pips DD to approximate dollar DD for a $1,000 account.
    Uses typical pip values per lot for different CCY groups.
    """
    abs_dd = abs(max_dd_pips)
    # Approximate $/pip for 0.01 lot (standard micro lot)
    # JPY pairs: ~$0.065/pip, Standard pairs: ~$0.10/pip, XAU: ~$0.01/pip
    if 'JPY' in symbol:
        dollar_per_pip = 0.065
    elif 'XAU' in symbol or 'XAG' in symbol:
        dollar_per_pip = 0.01  # XAU is quoted differently
    else:
        dollar_per_pip = 0.10  # Standard pairs like EURUSD, GBPUSD
    
    est_dollar_dd = abs_dd * dollar_per_pip
    pct = est_dollar_dd / 1000 * 100
    
    if pct <= 5:    return ('S', '#4CAF50', '≤5%')     # ≤$50
    elif pct <= 10: return ('A', '#8BC34A', '≤10%')    # ≤$100
    elif pct <= 20: return ('B', '#CDDC39', '≤20%')    # ≤$200
    elif pct <= 35: return ('C', '#FFC107', '≤35%')    # ≤$350
    elif pct <= 50: return ('D', '#FF9800', '≤50%')    # ≤$500
    else:           return ('F', '#F44336', '>50%')    # >$500


def fmt_pips(val):
    """Format pip value with $ prefix for USD display."""
    if abs(val) >= 1000:
        return f'${val:,.0f}'
    elif abs(val) >= 100:
        return f'${val:.0f}'
    else:
        return f'${val:.1f}'


def generate_html(all_results):
    """Generate the full ranking_ccy.html matching the gh-pages UI template."""

    scored = [r for r in all_results if not r['red_card']]
    red = [r for r in all_results if r['red_card']]

    # Build currency-pair aggregation
    by_ccy = defaultdict(list)
    for r in all_results:
        by_ccy[r['symbol']].append(r)

    # Symbol counts for filter dropdown
    sym_counts = Counter(r['symbol'] for r in all_results)
    sorted_syms = sorted(sym_counts.items())

    # Global stats
    total_pips = sum(r['total_net_pips'] for r in all_results)
    n_scored = len(scored)
    n_ccy = len(by_ccy)
    global_best = max(r['dde_v4'] for r in scored) if scored else 0
    today = datetime.now().strftime('%Y-%m-%d')

    # --- TOP 20 ---
    top20 = sorted(scored, key=lambda x: x['dde_v4'], reverse=True)[:20]

    # --- Best per Symbol ---
    best_per_sym = {}
    for r in sorted(scored, key=lambda x: x['dde_v4'], reverse=True):
        if r['symbol'] not in best_per_sym:
            best_per_sym[r['symbol']] = r
    best_sym_list = sorted(best_per_sym.values(), key=lambda x: x['dde_v4'], reverse=True)

    # --- ALL rows sorted by score (scored first, then red) ---
    all_sorted = sorted(scored, key=lambda x: x['dde_v4'], reverse=True) + \
                 sorted(red, key=lambda x: x['dde_v4'], reverse=True)

    # ── Table header HTML (reused across panels) ──
    thead_html = '''<thead><tr><th data-col="idx" data-type="num">#<span class="arrow"></span></th><th data-col="signal" data-type="num">Signal<span class="arrow"></span></th><th data-col="ea" data-type="str">EA<span class="arrow"></span></th><th data-col="symbol" data-type="str">CCY<span class="arrow"></span></th><th data-col="dde" data-type="num">DDE v4<span class="arrow"></span></th><th data-col="rr" data-type="num"><span class="tooltip" data-tip="Risk/Reward — 淨點數/最大虧損 (35%)">RR</span><span class="arrow"></span></th><th data-col="ml" data-type="num"><span class="tooltip" data-tip="Martin Layers — 馬丁層數 (25%)">ML</span><span class="arrow"></th><th data-col="wr" data-type="num"><span class="tooltip" data-tip="Win Rate — 勝率 ≥55%起計 (20%)">WR</span><span class="arrow"></span></th><th data-col="tc" data-type="num"><span class="tooltip" data-tip="Trade Count — 交易數量 ≥20起計 (15%)">TC</span><span class="arrow"></span></th><th data-col="ht" data-type="num"><span class="tooltip" data-tip="Holding Time — 平均持倉時間 (5%)">HT</span><span class="arrow"></span></th><th data-col="trades" data-type="num">Trades<span class="arrow"></span></th><th data-col="win" data-type="num">Win%<span class="arrow"></span></th><th data-col="pf" data-type="num">PF<span class="arrow"></span></th><th data-col="profit" data-type="num">Profit<span class="arrow"></span></th><th data-col="dd" data-type="num">Max DD<span class="arrow"></span></th><th data-col="dd1k" data-type="str"><span class="tooltip" data-tip="$1K 帳戶 DD 風險等級：S≤5% / A≤10% / B≤20% / C≤35% / D≤50% / F>50%（爆倉）">$1K DD</span><span class="arrow"></span></th><th data-col="wal" data-type="num">WAL<span class="arrow"></span></th><th data-col="lv" data-type="str">LV<span class="arrow"></span></th></tr></thead>'''

    def make_row(r, idx):
        """Generate a single table row."""
        is_red = r.get('red_card', False)
        rc_cls = ' class="rc"' if is_red else ''
        ea_style = get_ea_style(r['ea'])
        sc = get_score_class(r['dde_v4'])

        # DDE column
        if is_red:
            dde_cell = f'<td class="{sc}">{r["dde_v4"]:.1f} 🚫</td>'
        else:
            dde_cell = f'<td class="{sc}" data-val="{r["dde_v4"]}">{r["dde_v4"]:.1f}</td>'

        # DD class
        dd_cls = get_dd_class(r['max_dd_pips'])

        # Profit
        if is_red and r['total_net_pips'] < 0:
            profit_cell = f'<td>{fmt_pips(r["total_net_pips"])}</td>'
        else:
            profit_cell = f'<td data-val="{r["total_net_pips"]}">{fmt_pips(r["total_net_pips"])}</td>'

        # DD
        dd_cell = f'<td class="{dd_cls}" data-val="{r["max_dd_pips"]}">{fmt_pips(r["max_dd_pips"])}</td>'
        if is_red and abs(r['max_dd_pips']) < 500:
            dd_cell = f'<td class="{dd_cls}">{fmt_pips(r["max_dd_pips"])}</td>'

        # $1K DD Tier
        tier_letter, tier_color, tier_desc = get_dd_1k_tier(r['max_dd_pips'], r['symbol'])
        tier_cell = f'<td><span style="background:{tier_color};color:#fff;padding:1px 6px;border-radius:3px;font-size:0.85em;font-weight:bold" title="$1K DD ≈ {tier_desc}">{tier_letter}</span></td>'

        # PF
        pf = r['pf']
        pf_str = 'Inf' if pf > 999 else f'{pf:.1f}'

        # Win rate
        wr_str = f'{r["win_rate"]:.1f}%'

        # HT (avg_hold in hours → display as score)
        ht_val = r.get('ht', 0)

        # WAL
        wal_val = r.get('wal', 0)
        wal_str = f'{wal_val:.3f}' if wal_val != int(wal_val) else f'{wal_val:.1f}'

        return f'''<tr data-symbol="{r['symbol']}"{rc_cls}>
<td data-val="{idx}.0">{idx}</td>
<td><a href="https://signals.algoforest.com/signals/{r['signal_id']}">{r['signal_id']}</a> <a href="../detailed_comparison_all_levels_{r['signal_id']}.html">📊</a></td>
<td><span style="{ea_style};padding:1px 6px;border-radius:3px;font-size:0.8em;font-weight:bold">{r['ea']}</span></td>
<td style="font-weight:bold;color:var(--primary)">{r['symbol']}</td>
{dde_cell}
<td data-val="{r["rr"]}">{r["rr"]:.0f}</td><td data-val="{r["ml"]}">{r["ml"]:.0f}</td>
<td data-val="{r["wr"]}">{r["wr"]:.0f}</td><td data-val="{r["tc"]}">{r["tc"]:.0f}</td>
<td data-val="{ht_val}">{ht_val:.0f}</td>
<td data-val="{r["trades"]}">{r["trades"]:,}</td><td data-val="{r["win_rate"]}">{wr_str}</td>
<td data-val="{pf}">{pf_str}</td>
{profit_cell}
{dd_cell}
{tier_cell}
<td data-val="{wal_val}">{wal_str}</td>
<td>{r['lv']}</td>
</tr>
'''

    def make_rows(rows):
        return ''.join(make_row(r, i) for i, r in enumerate(rows, 1))

    # Symbol filter options
    sym_options = '<option value="">All Symbols (' + str(len(sorted_syms)) + ')</option>\n'
    sym_options += '\n'.join(
        f'<option value="{sym}">{sym} ({cnt})</option>'
        for sym, cnt in sorted_syms
    )

    html = f'''<!DOCTYPE html>
<html lang="zh-HK">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>💱 CCY 排名</title>
<style>
/* === Unified Theme System === */
:root{{--font-main:-apple-system,BlinkMacSystemFont,'Segoe UI','PingFang TC','Microsoft JhengHei',sans-serif;--radius:8px;--shadow:0 2px 8px rgba(0,0,0,0.12)}}
[data-theme="dark"]{{--bg:#0a0e17;--bg-card:#111520;--bg-hover:#1a1f2e;--text:#d0d0d0;--text2:#888;--primary:#FFD700;--accent:#64b5f6;--green:#4CAF50;--red:#FF5722;--yellow:#FFC107;--orange:#fd7e14;--border:#1e2433;--th-bg:#111520;--nav-bg:transparent;--grade-a:#4CAF50;--grade-b:#FFC107;--grade-c:#fd7e14;--grade-d:#FF5722;--header-from:#1a1f2e;--header-to:#0a0e17}}
[data-theme="light"]{{--bg:#f5f7fa;--bg-card:#ffffff;--bg-hover:#eef2f7;--text:#333;--text2:#666;--primary:#0f3460;--accent:#e94560;--green:#28a745;--red:#dc3545;--yellow:#ffc107;--orange:#fd7e14;--border:#ddd;--th-bg:#eef2f7;--nav-bg:rgba(0,0,0,0.03);--grade-a:#28a745;--grade-b:#ffc107;--grade-c:#fd7e14;--grade-d:#dc3545;--header-from:#0f3460;--header-to:#16213e}}
*{{transition:background-color .25s ease,color .25s ease,border-color .25s ease}}
.theme-toggle{{width:36px;height:36px;border:1px solid var(--border);border-radius:50%;background:var(--bg-card);color:var(--text);font-size:18px;cursor:pointer;display:flex;align-items:center;justify-content:center;box-shadow:var(--shadow);line-height:1;padding:0;flex-shrink:0}}.theme-toggle:hover{{background:var(--bg-hover);transform:scale(1.1)}}

/* Topnav */
.topnav{{display:flex;align-items:center;gap:12px;padding:10px 16px;background:var(--bg-card);border-bottom:1px solid var(--border);margin-bottom:16px;position:sticky;top:0;z-index:100}}
.topnav-logo{{font-weight:700;font-size:1em;color:var(--primary);text-decoration:none;margin-right:auto}}
.topnav-links{{display:flex;gap:10px;flex-wrap:wrap}}
.topnav-link{{color:var(--text2);text-decoration:none;font-size:.88em;font-weight:600;padding:4px 10px;border-radius:6px;transition:all .2s}}
.topnav-link:hover{{color:var(--primary);background:var(--bg-hover)}}
.topnav-link.active{{color:var(--primary);background:var(--bg-hover)}}
/* End Theme System */

*{{margin:0;padding:0;box-sizing:border-box}}
body{{font-family:-apple-system,BlinkMacSystemFont,sans-serif;background:var(--bg);color:var(--text);padding:16px;max-width:1400px;margin:0 auto}}
h1{{font-size:1.3em;margin-bottom:4px;color:var(--primary)}}
.info-tip:hover .info-tip-text{{display:block}}.sub{{color:var(--text2);font-size:0.85em;margin-bottom:16px}}
.stats{{background:var(--bg-card);border:1px solid var(--border);border-radius:8px;padding:12px 18px;margin-bottom:16px;display:flex;gap:30px;flex-wrap:wrap}}
.stats .v{{font-size:1.5em;font-weight:bold;color:var(--primary)}}
.stats .l{{font-size:0.75em;color:var(--text2)}}
select{{background:var(--bg-card);border:1px solid var(--border);color:var(--text);padding:8px 12px;border-radius:6px;margin-bottom:12px;font-size:14px}}
table{{width:100%;border-collapse:collapse;min-width:700px}}
th{{background:var(--bg-card);padding:8px 10px;text-align:left;border-bottom:2px solid var(--primary);color:var(--primary);font-size:0.8em;white-space:nowrap;cursor:pointer;user-select:none}}
th:hover{{background:var(--bg-hover)}}
th .arrow{{font-size:0.65em;margin-left:3px;opacity:0.3}}
th.asc .arrow{{opacity:1}}
th.desc .arrow{{opacity:1}}
td{{padding:6px 10px;border-bottom:1px solid var(--border);font-size:0.9em}}
tr:hover{{background:var(--bg-card)}}
tr.rc{{opacity:0.4}}
a{{color:var(--accent);text-decoration:none;font-weight:bold}}
a:hover{{text-decoration:underline}}
.container{{overflow-x:auto}}
label{{color:var(--text2);font-size:0.9em;margin-left:12px}}
input[type=text]{{background:var(--bg-card);border:1px solid var(--border);color:var(--text);padding:8px 12px;border-radius:6px;font-size:14px;width:160px}}
input[type=text]::placeholder{{color:#555}}
.s0{{color:#e57373}}.s75{{color:#ffb74d}}.s85{{color:#aed581}}.s90{{color:#81c784}}
.dd-g{{color:#81c784}}.dd-y{{color:#ffb74d}}.dd-r{{color:#e57373}}
.hideRC{{display:none}}
.tabs{{display:flex;gap:0;margin-bottom:0}}
.tab{{padding:10px 20px;background:var(--bg-card);border:1px solid var(--border);color:var(--text2);cursor:pointer;border-radius:8px 8px 0 0;font-size:0.95em}}
.tab.active{{background:var(--bg);color:var(--primary);border-bottom-color:var(--bg);font-weight:bold}}
.tab:hover{{color:var(--text)}}
.panel{{background:var(--bg);border:1px solid var(--border);border-top:none;border-radius:0 0 8px 8px;padding:16px}}
.panel.hidden{{display:none}}

.tooltip{{position:relative;cursor:help}}
.tooltip::after{{content:attr(data-tip);position:absolute;bottom:120%;left:50%;transform:translateX(-50%);background:var(--bg-hover);border:1px solid #333;color:#ddd;font-size:0.75em;padding:6px 10px;border-radius:6px;white-space:nowrap;opacity:0;pointer-events:none;transition:opacity 0.2s;z-index:99;font-weight:normal}}
.tooltip:hover::after{{opacity:1}}

@media(max-width:768px){{body{{padding:8px;font-size:12px}}.tab{{padding:8px 12px;font-size:0.85em}}}}
</style>

<script>
(function(){{
  const saved=localStorage.getItem('tsa-theme');
  const t=saved||'dark';
  document.documentElement.setAttribute('data-theme',t);
  document.addEventListener('DOMContentLoaded',function(){{
    const btn=document.getElementById('theme-toggle');
    if(btn)btn.textContent=t==='dark'?'☀️':'🌙';
  }});
}})();
function toggleTheme(){{
  const cur=document.documentElement.getAttribute('data-theme');
  const next=cur==='dark'?'light':'dark';
  document.documentElement.setAttribute('data-theme',next);
  localStorage.setItem('tsa-theme',next);
  const btn=document.getElementById('theme-toggle');
  if(btn)btn.textContent=next==='dark'?'☀️':'🌙';
}}
</script>

</head>
<body>
<div class="topnav">
<a href="../index.html" class="topnav-logo">🦀 TSA</a>
<div class="topnav-links">
<a href="../signal_ranking.html" class="topnav-link">🏆 Signal 排名</a><a href="./ccy_ranking.html" class="topnav-link active">💱 CCY 排名</a><a href="./symbol_ranking.html" class="topnav-link">📊 波幅波</a><a href="./volatility.html" class="topnav-link">📈 波幅表</a>
</div>
<button class="theme-toggle" id="theme-toggle" onclick="toggleTheme()" title="切換亮/暗模式"></button>
</div>

<h1>💱 CCY 排名</h1>
<div style="display:flex;align-items:center;gap:8px;margin-bottom:12px;font-size:0.82em;color:var(--text2)"><span>{today}</span><span class="info-tip" style="position:relative;display:inline-flex;cursor:pointer"><span style="width:18px;height:18px;border-radius:50%;background:var(--bg-hover);border:1px solid var(--border);display:inline-flex;align-items:center;justify-content:center;font-size:12px;font-style:italic;color:var(--text2)">i</span><span class="info-tip-text" style="display:none;position:absolute;top:24px;left:0;background:var(--bg-card);border:1px solid var(--border);border-radius:8px;padding:10px 14px;font-size:0.82em;line-height:1.6;z-index:50;white-space:nowrap;box-shadow:0 4px 16px rgba(0,0,0,0.3);color:var(--text)">Lot-based Martin Layer（SET file 參數）<br>滑鼠 Hover 欄位簡稱可看公式說明</span></span></div>

<div class="stats">
<div><div class="v">{len(all_results)}</div><div class="l">Total</div></div>
<div><div class="v">{n_scored}</div><div class="l">Scored</div></div>
<div><div class="v">{n_ccy}</div><div class="l">CCY</div></div>
<div><div class="v">{global_best}</div><div class="l">最高分</div></div>
<div><div class="v">{fmt_pips(total_pips)}</div><div class="l">Total P&L</div></div>
</div>

<div class="tabs">
<div class="tab active" onclick="showPanel('top20',this)">🏆 TOP 20</div>
<div class="tab" onclick="showPanel('bestsym',this)">💱 各 CCY 最佳</div>
<div class="tab" onclick="showPanel('all',this)">📋 全部明細</div>
</div>

<!-- ============ PANEL 1: TOP 20 ============ -->
<div id="panel-top20" class="panel">
<h2 style="color:var(--primary);font-size:1em;margin:0 0 12px">🏆 DDE v4 總排名 Top 20 <span style="font-size:0.7em;color:var(--text2);font-weight:normal">(點擊欄位排序)</span></h2>
<div class="container"><table id="tbl-top20">{thead_html}<tbody>
{make_rows(top20)}
</tbody></table>
<p style="color:var(--text2);font-size:0.8em;margin-top:8px">共 {n_scored} 個 scored rows，顯示前 20</p>
</div></div>

<!-- ============ PANEL 2: BEST PER SYMBOL ============ -->
<div id="panel-bestsym" class="panel hidden">
<h2 style="color:var(--primary);font-size:1em;margin:0 0 12px">💱 每個 Symbol 最高分的 Signal <span style="font-size:0.7em;color:var(--text2);font-weight:normal">(點擊欄位排序)</span></h2>
<div class="container"><table id="tbl-bestsym">{thead_html}<tbody>
{make_rows(best_sym_list)}
</tbody></table>
<p style="color:var(--text2);font-size:0.8em;margin-top:8px">{n_ccy} 個 symbols，每個只顯示最佳 Signal</p>
</div></div>

<!-- ============ PANEL 3: ALL DETAIL ============ -->
<div id="panel-all" class="panel hidden">
<h2 style="color:var(--primary);font-size:1em;margin:0 0 12px">📋 全部明細</h2>
<select id="symSel" onchange="filterSymbol()">{sym_options}</select>
<label><input type="checkbox" id="hideRC" onchange="applyFilters()"> 隱藏紅牌</label>
<span style="margin-left:12px"><input type="text" id="eaSel" placeholder="篩選 EA..." oninput="applyFilters()"> <input type="text" id="sigSel" placeholder="Signal ID..." oninput="applyFilters()"></span>
<span style="color:var(--text2);font-size:0.8em;margin-left:8px" id="rowCount"></span>
<div class="container">
<table id="tbl">{thead_html}<tbody>
{make_rows(all_sorted)}
</tbody></table></div>
</div>

<script>
/* ── Tab switching ── */
function showPanel(id,el){{
  document.querySelectorAll('.panel').forEach(function(p){{p.classList.add('hidden')}});
  document.querySelectorAll('.tab').forEach(function(t){{t.classList.remove('active')}});
  document.getElementById('panel-'+id).classList.remove('hidden');
  el.classList.add('active');
}}

/* ── Sorting ── */
function getCellValue(row, colIdx, type) {{
  var cell = row.cells[colIdx];
  if (!cell) return type === 'num' ? 0 : '';
  var dv = cell.getAttribute('data-val');
  if (dv !== null) return type === 'num' ? parseFloat(dv) : dv;
  var text = cell.textContent.trim().replace(/[^0-9.\\-]/g, '');
  return type === 'num' ? (parseFloat(text) || 0) : cell.textContent.trim();
}}

function sortTable(table, colIdx, type) {{
  var tbody = table.tBodies[0];
  var rows = Array.from(tbody.querySelectorAll('tr'));
  var ths = table.querySelectorAll('thead th');
  var dir = ths[colIdx].classList.contains('asc') ? 'desc' : 'asc';
  ths.forEach(function(h) {{ h.classList.remove('asc', 'desc'); }});
  ths[colIdx].classList.add(dir);
  rows.sort(function(a, b) {{
    var va = getCellValue(a, colIdx, type);
    var vb = getCellValue(b, colIdx, type);
    if (type === 'num') return dir === 'asc' ? va - vb : vb - va;
    return dir === 'asc' ? String(va).localeCompare(String(vb)) : String(vb).localeCompare(String(va));
  }});
  rows.forEach(function(r) {{ tbody.appendChild(r); }});
  // Re-number # column for all-detail table
  if (table.id === 'tbl') {{
    var n = 0;
    tbody.querySelectorAll('tr').forEach(function(r) {{
      if (r.style.display !== 'none') {{ n++; r.cells[0].textContent = n; }}
    }});
  }}
}}

// Attach click handlers
document.querySelectorAll('table[id^="tbl"]').forEach(function(table) {{
  table.querySelectorAll('thead th').forEach(function(th, i) {{
    th.addEventListener('click', function() {{
      sortTable(table, i, th.getAttribute('data-type') || 'str');
    }});
  }});
}});

/* ── Filtering (All Details) ── */
function applyFilters() {{
  var sym = document.getElementById('symSel').value;
  var hideRC = document.getElementById('hideRC').checked;
  var eaF = document.getElementById('eaSel').value.trim().toUpperCase();
  var sigF = document.getElementById('sigSel').value.trim();
  var rows = document.querySelectorAll('#tbl tbody tr');
  var vis = 0;
  rows.forEach(function(r) {{
    var show = true;
    if (sym && r.dataset.symbol !== sym) show = false;
    if (hideRC && r.classList.contains('rc')) show = false;
    if (show && eaF) {{
      var ea = r.cells[15]; if (!ea || ea.textContent.toUpperCase().indexOf(eaF) === -1) show = false;
    }}
    if (show && sigF) {{
      var sig = r.cells[1]; if (!sig || sig.textContent.indexOf(sigF) === -1) show = false;
    }}
    r.style.display = show ? '' : 'none';
    if (show) vis++;
  }});
  document.getElementById('rowCount').textContent = '顯示 ' + vis + ' / ' + rows.length;
}}
function filterSymbol() {{ applyFilters(); }}
function toggleRC() {{ applyFilters(); }}

// Init count
var total = document.querySelectorAll('#tbl tbody tr').length;
document.getElementById('rowCount').textContent = '顯示 ' + total + ' / ' + total;
</script>
</body></html>'''

    return html


def main():
    pkl_path = '/tmp/dde_v4_data.pkl'
    if not Path(pkl_path).exists():
        print("❌ Run dde_v4_scorer.py first to generate /tmp/dde_v4_data.pkl")
        sys.exit(1)

    with open(pkl_path, 'rb') as f:
        all_results = pickle.load(f)

    print(f"Loaded {len(all_results)} rows from pickle")

    html = generate_html(all_results)
    output_path = REPORTS_DIR / 'ranking_ccy.html'
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html)

    print(f"✅ Generated: {output_path} ({len(html):,} bytes)")
    print(f"   Total rows: {len(all_results)}")


if __name__ == '__main__':
    main()
