#!/usr/bin/env python3
"""
Generate Currency Pair Ranking HTML (DDE v4 — pip-based)
All Profit/MaxDD values are in pips (not USD).
Reads from the pickle generated by dde_v4_scorer.py.
"""
import pickle
import sys
from pathlib import Path
from collections import defaultdict
from datetime import datetime

BASE_DIR = Path(__file__).parent
REPORTS_DIR = BASE_DIR / 'reports'
REPORTS_DIR.mkdir(exist_ok=True)


def get_score_class(score):
    if score >= 90: return 's90'
    elif score >= 80: return 's80'
    elif score >= 70: return 's70'
    elif score >= 60: return 's60'
    else: return 's0'

def get_dd_class(dd_value):
    """Pip-based DD thresholds: 500 / 2000 pips"""
    abs_dd = abs(dd_value)
    if abs_dd < 500:
        return 'dd-g'
    elif abs_dd < 2000:
        return 'dd-y'
    else:
        return 'dd-r'

def get_ea_style(ea_tag):
    parts = ea_tag.split('/')
    colors = {
        'DW': ('#1b5e20', '#a5d6a7'),
        'SMA': ('#0d47a1', '#90caf9'),
        'MKD': ('#4a148c', '#ce93d8'),
        'S10': ('#e65100', '#ffcc80'),
        'Flash': ('#b71c1c', '#ef9a9a'),
        'GEM': ('#004d40', '#80cbc4'),
        'UNK': ('#37474f', '#b0bec5'),
    }
    bg, fg = colors.get(parts[0], ('#37474f', '#b0bec5'))
    return f'background:{bg};color:{fg}'

def fmt_pips(val):
    """Format pip value without $ prefix"""
    if abs(val) >= 1000:
        return f'{val:,.0f}'
    elif abs(val) >= 100:
        return f'{val:.0f}'
    else:
        return f'{val:.1f}'

def fmt_pips_compact(val):
    """Compact pip display for table"""
    if val >= 10000:
        return f'{val/1000:.1f}k'
    return f'{val:,.0f}'


def generate_html(all_results):
    """Generate the full ranking_ccy.html from pip-based data."""

    # Separate scored vs red-card
    scored = [r for r in all_results if not r['red_card']]
    red = [r for r in all_results if r['red_card']]

    # Build currency-pair aggregation
    by_ccy = defaultdict(list)
    for r in all_results:
        by_ccy[r['symbol']].append(r)

    ccy_stats = {}
    for sym, rows in by_ccy.items():
        total_pips = sum(r['total_profit'] for r in rows)
        total_trades = sum(r['trades'] for r in rows)
        wins = sum(1 for r in rows for _ in range(int(r['win_rate'] * r['trades'] / 100)))
        avg_score = sum(r['dde_v4'] for r in rows) / len(rows) if rows else 0
        ccy_stats[sym] = {
            'total_pips': total_pips,
            'total_trades': total_trades,
            'signals': len(rows),
            'avg_score': round(avg_score, 1),
        }

    # Global stats (pip-based)
    total_pips = sum(r['total_profit'] for r in all_results)
    total_signals = len(set(r['signal_id'] for r in all_results))
    global_avg = round(sum(r['dde_v4'] for r in scored) / len(scored), 1) if scored else 0
    global_best = max(r['dde_v4'] for r in scored) if scored else 0
    global_worst = min(r['dde_v4'] for r in scored) if scored else 0

    now = datetime.now().strftime('%Y-%m-%d %H:%M')

    # --- TOP 20 ---
    top20 = sorted(scored, key=lambda x: x['dde_v4'], reverse=True)[:20]

    # --- Best per Symbol ---
    best_per_sym = {}
    for r in sorted(scored, key=lambda x: x['dde_v4'], reverse=True):
        if r['symbol'] not in best_per_sym:
            best_per_sym[r['symbol']] = r
    best_sym_list = sorted(best_per_sym.values(), key=lambda x: x['dde_v4'], reverse=True)

    # --- ALL rows sorted by score ---
    all_sorted = sorted(scored, key=lambda x: x['dde_v4'], reverse=True)

    def make_rows(rows, start_rank=1):
        html = ''
        for i, r in enumerate(rows, start_rank):
            medal = ''
            row_cls = ''
            if i == 1: medal, row_cls = '🥇', ' class="top3"'
            elif i == 2: medal, row_cls = '🥈', ' class="top3"'
            elif i == 3: medal, row_cls = '🥉', ' class="top3"'
            else: medal = str(i)

            sc = get_score_class(r['dde_v4'])
            dd_cls = get_dd_class(r['max_dd'])
            ea_style = get_ea_style(r['ea'])
            profit_cls = 'g' if r['total_profit'] >= 0 else 'r'

            pf = r['pf']
            pf_str = 'Inf' if pf > 999 else f'{pf:.1f}'

            # avg hold in days
            hold_days = r['avg_hold'] / 24
            hold_str = f'{hold_days:.1f}d' if hold_days >= 1 else f'{r["avg_hold"]:.0f}h'

            html += f'''<tr{row_cls} data-symbol="{r['symbol']}">
<td data-val="{i}">{medal}</td>
<td><a href="https://signals.algoforest.com/signals/{r['signal_id']}" target="_blank">{r['signal_id']}</a> <a href="../detailed_comparison_all_levels_{r['signal_id']}.html" target="_blank">📊</a></td>
<td style="font-weight:bold;color:#64b5f6">{r['symbol']}</td>
<td class="{sc}" data-val="{r['dde_v4']}">{r['dde_v4']}</td>
<td data-val="{r['rr']}">{r['rr']:.0f}</td><td data-val="{r['ml']}">{r['ml']:.0f}</td>
<td data-val="{r['wr']}">{r['wr']:.0f}</td><td data-val="{r['tc']}">{r['tc']:.0f}</td>
<td data-val="{r['ht']}">{r['ht']:.0f}</td>
<td data-val="{r['trades']}">{r['trades']:,}</td><td data-val="{r['win_rate']}">{r['win_rate']:.1f}%</td>
<td data-val="{pf}">{pf_str}</td>
<td class="{profit_cls}" data-val="{r['total_profit']}">{fmt_pips(r["total_profit"])} pips</td>
<td class="m {dd_cls}" data-val="{r['max_dd']}">{fmt_pips(r["max_dd"])} pips</td>
<td data-val="{r['wal']}">{r['wal']:.1f}</td>
<td><span style="{ea_style};padding:1px 6px;border-radius:3px;font-size:0.8em;font-weight:bold">{r['ea']}</span></td>
<td>{r['lv']}</td>
</tr>
'''
        return html

    # Red card rows
    red_rows = ''
    for i, r in enumerate(sorted(red, key=lambda x: x['signal_id']), 1):
        ea_style = get_ea_style(r['ea'])
        red_rows += f'''<tr data-symbol="{r['symbol']}">
<td>{i}</td>
<td><a href="https://signals.algoforest.com/signals/{r['signal_id']}" target="_blank">{r['signal_id']}</a></td>
<td style="font-weight:bold;color:#64b5f6">{r['symbol']}</td>
<td class="s0" data-val="0">🚫</td>
<td colspan="5" style="color:#FF5722;font-size:0.85em">{", ".join(r["red_reasons"])}</td>
<td data-val="{r['trades']}">{r['trades']:,}</td>
<td>{r['win_rate']:.1f}%</td>
<td>-</td><td>-</td><td>-</td>
<td data-val="{r['wal']}">{r['wal']:.1f}</td>
<td><span style="{ea_style};padding:1px 6px;border-radius:3px;font-size:0.8em;font-weight:bold">{r['ea']}</span></td>
<td>{r['lv']}</td>
</tr>
'''

    # Currency pair summary table
    ccy_summary_rows = ''
    for i, (sym, stats) in enumerate(sorted(ccy_stats.items(), key=lambda x: x[1]['avg_score'], reverse=True), 1):
        sc = get_score_class(stats['avg_score'])
        ccy_summary_rows += f'''<tr>
<td>{i}</td>
<td style="font-weight:bold;color:#64b5f6">{sym}</td>
<td class="{sc}">{stats['avg_score']}</td>
<td>{stats['signals']}</td>
<td>{stats['total_trades']:,}</td>
<td>{"{:+,.1f}".format(stats["total_pips"])} pips</td>
</tr>
'''

    html = f'''<!DOCTYPE html>
<html lang="zh-HK">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Currency Ranking — DDE v4 (Pips)</title>
<style>
*{{margin:0;padding:0;box-sizing:border-box}}
body{{font-family:-apple-system,BlinkMacSystemFont,sans-serif;background:#0a0e17;color:#d0d0d0;padding:12px;font-size:13px}}
h1{{color:#FFD700;font-size:1.2em;margin-bottom:2px}}
.nav{{margin-bottom:12px}}.nav a{{color:#FFD700;text-decoration:none;margin-right:12px}}.nav a:hover{{text-decoration:underline}}
.sub{{color:#666;font-size:0.85em;margin-bottom:12px}}
.sum{{background:#111520;border:1px solid #1e2433;border-radius:6px;padding:10px 14px;margin-bottom:12px;display:flex;flex-wrap:wrap;gap:20px}}
.sum .v{{font-size:1.3em;font-weight:bold;color:#FFD700}}.sum .l{{font-size:0.7em;color:#666}}
.tabs{{display:flex;gap:2px;margin-bottom:12px}}
.tab{{background:#111520;border:1px solid #1e2433;border-bottom:none;color:#666;padding:8px 16px;cursor:pointer;border-radius:6px 6px 0 0;font-size:0.9em}}
.tab.active{{background:#0a0e17;color:#FFD700;border-color:#FFD700;border-bottom:1px solid #0a0e17}}
.panel{{background:#0a0e17;border:1px solid #1e2433;border-radius:0 6px 6px 6px;padding:12px;display:none}}
.panel.active{{display:block}}
.container{{overflow-x:auto}}
table{{width:100%;min-width:900px;border-collapse:collapse}}
thead th{{background:#111520;padding:6px 8px;text-align:left;border-bottom:2px solid #FFD700;color:#FFD700;font-size:0.75em;white-space:nowrap;user-select:none}}
thead th .fr{{margin-top:3px}}
thead th input{{background:#0a0e17;border:1px solid #1e2433;color:#d0d0d0;padding:3px 5px;border-radius:3px;font-size:0.85em;width:100%;max-width:80px}}
tbody td{{padding:5px 8px;border-bottom:1px solid #1a1f2e}}
tbody tr:hover{{background:#111520}}
tbody tr.top3{{background:rgba(255,215,0,0.03)}}
a{{color:#64b5f6;text-decoration:none}}a:hover{{text-decoration:underline}}
.sym{{color:#64b5f6;font-weight:bold}}
.s90{{color:#4CAF50;font-weight:bold}}.s80{{color:#8BC34A;font-weight:bold}}.s70{{color:#FFC107;font-weight:bold}}.s0{{color:#FF5722;font-weight:bold}}
.g{{color:#4CAF50}}.r{{color:#FF5722}}
.m{{font-family:'SF Mono',Consolas,monospace;font-size:0.9em}}
.dd-g{{color:#4CAF50}}.dd-y{{color:#FFC107}}.dd-r{{color:#FF5722}}
.tooltip{{position:relative;cursor:help;border-bottom:1px dotted #FFD700}}
.tooltip:hover::after{{content:attr(data-tip);position:absolute;bottom:100%;left:50%;transform:translateX(-50%);background:#1a1f2e;color:#d0d0d0;padding:4px 8px;border-radius:4px;font-size:0.85em;white-space:nowrap;z-index:99;border:1px solid #FFD700}}
.note{{background:#111520;border:1px solid #1e2433;border-radius:6px;padding:10px 14px;margin-bottom:12px;color:#999;font-size:0.85em}}
@media(max-width:768px){{body{{font-size:11px}}thead th input{{max-width:60px}}}}
</style>
</head>
<body>
<h1>📊 Currency Pair Ranking — DDE v4 (Pips)</h1>
<div class="nav"><a href="../index.html">🏠 首頁</a><a href="./index.html">📈 報告索引</a><a href="./ranking.html">🏆 Signal 排名</a></div>
<div class="sub">按 Signal×Symbol 排名 | 所有盈虧以 Pips 計算 | DDE v4 五維度評分 | {now}</div>
<div class="note">💡 計價單位已由美金改為 <b>Pips</b>。Profit = 總淨點數，Max DD = 最大累計回撤點數，PF = 盈利點數/虧損點數</div>
<div class="sum">
<div><div class="v">{"{:+,.1f}".format(total_pips)}</div><div class="l">Total Pips P&L</div></div>
<div><div class="v">{len(all_results)}</div><div class="l">Total Rows</div></div>
<div><div class="v">{len(scored)}</div><div class="l">Scored</div></div>
<div><div class="v">{len(red)}</div><div class="l">Red Card</div></div>
<div><div class="v">{global_avg}</div><div class="l">Avg Score</div></div>
<div><div class="v">{global_best}</div><div class="l">Best</div></div>
<div><div class="v">{global_worst}</div><div class="l">Worst</div></div>
</div>

<div class="tabs">
<div class="tab active" onclick="showPanel('top20')">🏆 TOP 20</div>
<div class="tab" onclick="showPanel('bestsym')">💱 Best/Symbol</div>
<div class="tab" onclick="showPanel('all')">📋 All Scored ({len(scored)})</div>
<div class="tab" onclick="showPanel('red')">🚫 Red Cards ({len(red)})</div>
<div class="tab" onclick="showPanel('ccy')">📊 Currency Summary ({len(ccy_stats)})</div>
</div>

<div id="panel-top20" class="panel active">
<div class="container"><table id="tbl-top20"><thead><tr>
<th data-col="idx" data-type="num">#<span class="arrow"></span></th>
<th data-col="signal" data-type="num">Signal<span class="arrow"></span></th>
<th data-col="symbol" data-type="str">Symbol<span class="arrow"></span></th>
<th data-col="dde" data-type="num">DDE v4<span class="arrow"></span></th>
<th data-col="rr" data-type="num"><span class="tooltip" data-tip="Risk/Reward — 淨點數/最大虧損 (35%)">RR</span><span class="arrow"></span></th>
<th data-col="ml" data-type="num"><span class="tooltip" data-tip="Martin Layers — 馬丁層數 (25%)">ML</span><span class="arrow"></span></th>
<th data-col="wr" data-type="num"><span class="tooltip" data-tip="Win Rate — 勝率 ≥55%起計 (20%)">WR</span><span class="arrow"></span></th>
<th data-col="tc" data-type="num"><span class="tooltip" data-tip="Trade Count — 交易數量 ≥20起計 (15%)">TC</span><span class="arrow"></span></th>
<th data-col="ht" data-type="num"><span class="tooltip" data-tip="Holding Time — 平均持倉時間 (5%)">HT</span><span class="arrow"></span></th>
<th data-col="trades" data-type="num">Trades<span class="arrow"></span></th>
<th data-col="win" data-type="num">Win%<span class="arrow"></span></th>
<th data-col="pf" data-type="num">PF<span class="arrow"></span></th>
<th data-col="profit" data-type="num">Profit (pips)<span class="arrow"></span></th>
<th data-col="dd" data-type="num">Max DD (pips)<span class="arrow"></span></th>
<th data-col="wal" data-type="num">WAL<span class="arrow"></span></th>
<th data-col="ea" data-type="str">EA<span class="arrow"></span></th>
<th data-col="lv" data-type="str">LV<span class="arrow"></span></th>
</tr></thead><tbody>
{make_rows(top20)}
</tbody></table></div>
</div>

<div id="panel-bestsym" class="panel">
<div class="container"><table id="tbl-bestsym"><thead><tr>
<th data-col="idx" data-type="num">#<span class="arrow"></span></th>
<th data-col="signal" data-type="num">Signal<span class="arrow"></span></th>
<th data-col="symbol" data-type="str">Symbol<span class="arrow"></span></th>
<th data-col="dde" data-type="num">DDE v4<span class="arrow"></span></th>
<th data-col="rr" data-type="num">RR<span class="arrow"></span></th>
<th data-col="ml" data-type="num">ML<span class="arrow"></span></th>
<th data-col="wr" data-type="num">WR<span class="arrow"></span></th>
<th data-col="tc" data-type="num">TC<span class="arrow"></span></th>
<th data-col="ht" data-type="num">HT<span class="arrow"></span></th>
<th data-col="trades" data-type="num">Trades<span class="arrow"></span></th>
<th data-col="win" data-type="num">Win%<span class="arrow"></span></th>
<th data-col="pf" data-type="num">PF<span class="arrow"></span></th>
<th data-col="profit" data-type="num">Profit (pips)<span class="arrow"></span></th>
<th data-col="dd" data-type="num">Max DD (pips)<span class="arrow"></span></th>
<th data-col="wal" data-type="num">WAL<span class="arrow"></span></th>
<th data-col="ea" data-type="str">EA<span class="arrow"></span></th>
<th data-col="lv" data-type="str">LV<span class="arrow"></span></th>
</tr></thead><tbody>
{make_rows(best_sym_list)}
</tbody></table></div>
</div>

<div id="panel-all" class="panel">
<div class="container"><table id="tbl-all"><thead><tr>
<th>#</th><th>Signal</th><th>Symbol</th><th>DDE v4</th>
<th>RR</th><th>ML</th><th>WR</th><th>TC</th><th>HT</th>
<th>Trades</th><th>Win%</th><th>PF</th>
<th>Profit (pips)</th><th>Max DD (pips)</th><th>WAL</th><th>EA</th><th>LV</th>
</tr></thead><tbody>
{make_rows(all_sorted)}
</tbody></table></div>
</div>

<div id="panel-red" class="panel">
<div class="container"><table><thead><tr>
<th>#</th><th>Signal</th><th>Symbol</th><th>Status</th><th>Reason</th>
<th>Trades</th><th>Win%</th><th>WAL</th><th>EA</th><th>LV</th>
</tr></thead><tbody>
{red_rows}
</tbody></table></div>
</div>

<div id="panel-ccy" class="panel">
<div class="container"><table><thead><tr>
<th>#</th><th>Symbol</th><th>Avg Score</th><th>Signals</th><th>Total Trades</th><th>Total Pips</th>
</tr></thead><tbody>
{ccy_summary_rows}
</tbody></table></div>
</div>

<script>
function showPanel(id) {{
    document.querySelectorAll('.panel').forEach(p => p.classList.remove('active'));
    document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
    document.getElementById('panel-'+id).classList.add('active');
    event.target.classList.add('active');
}}
</script>
</body></html>'''

    return html


def main():
    pkl_path = '/tmp/dde_v4_data.pkl'
    if not Path(pkl_path).exists():
        print("❌ Run dde_v4_scorer.py first to generate /tmp/dde_v4_data.pkl")
        sys.exit(1)

    with open(pkl_path, 'rb') as f:
        all_results = pickle.load(f)

    print(f"Loaded {len(all_results)} rows from pickle")

    html = generate_html(all_results)
    output_path = REPORTS_DIR / 'ranking_ccy.html'
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html)

    print(f"✅ Generated: {output_path} ({len(html):,} bytes)")
    print(f"   Total rows: {len(all_results)}")


if __name__ == '__main__':
    main()
