#!/usr/bin/env python3
"""
Generate CCY Ranking HTML (DDE v5 — ranking-based, 4 dimensions)
WR 15% + PF 20% + DD 25% + Martin 40%

Reads from the pickle generated by dde_v5_scorer.py.
"""
import pickle
import sys
from pathlib import Path
from collections import defaultdict, Counter
from datetime import datetime

BASE_DIR = Path(__file__).parent
REPORTS_DIR = BASE_DIR / 'reports'
OUTPUT_DIR = BASE_DIR / 'output'
DOCS_DIR = BASE_DIR / 'docs'
REPORTS_DIR.mkdir(exist_ok=True)
OUTPUT_DIR.mkdir(exist_ok=True)
DOCS_DIR.mkdir(exist_ok=True)

EA_COLORS = {
    'DW':      ('#4a148c', '#ce93d8'),
    'SMA':     ('#1b5e20', '#a5d6a7'),
    'SMAPro':  ('#1b5e20', '#c8e6c9'),
    'MKD':     ('#e65100', '#ffcc80'),
    'MKDPro':  ('#bf360c', '#ffab91'),
    'Flash':   ('#0d47a1', '#90caf9'),
    'S10':     ('#004d40', '#80cbc4'),
    'GC':      ('#0d47a1', '#90caf9'),
    'GS':      ('#1a237e', '#9fa8da'),
    'MAN':     ('#4527a0', '#b39ddb'),
    'UNK':     ('#333', 'var(--text2)'),
}


def get_ea_style(ea_tag):
    first = ea_tag.split('/')[0]
    bg, fg = EA_COLORS.get(first, EA_COLORS['UNK'])
    return f'background:{bg};color:{fg}'


def get_score_class(score):
    if score >= 90: return 's90'
    elif score >= 80: return 's80'
    elif score >= 70: return 's70'
    elif score >= 60: return 's60'
    else: return 's0'


def get_dd_class(dd_value):
    abs_dd = abs(dd_value)
    if abs_dd < 500: return 'dd-g'
    elif abs_dd < 2000: return 'dd-y'
    else: return 'dd-r'


def fmt_pips(val):
    if abs(val) >= 1000:
        return f'{val:,.0f}'
    elif abs(val) >= 100:
        return f'{val:.0f}'
    else:
        return f'{val:.1f}'


def generate_html(all_results):
    """Generate the full ranking_ccy.html with v5 data."""

    scored = [r for r in all_results if not r['red_card']]
    red = [r for r in all_results if r['red_card']]

    # Build currency-pair aggregation
    by_ccy = defaultdict(list)
    for r in all_results:
        by_ccy[r['symbol']].append(r)

    # Symbol counts for filter dropdown
    sym_counts = Counter(r['symbol'] for r in all_results)
    sorted_syms = sorted(sym_counts.items())

    # Global stats
    total_pips = sum(r['total_net_pips'] for r in all_results)
    n_scored = len(scored)
    n_ccy = len(by_ccy)
    global_best = max(r['dde_v5'] for r in scored) if scored else 0
    today = datetime.now().strftime('%Y-%m-%d')

    # --- TOP 20 ---
    top20 = sorted(scored, key=lambda x: x['dde_v5'], reverse=True)[:20]

    # --- Best per Symbol ---
    best_per_sym = {}
    for r in sorted(scored, key=lambda x: x['dde_v5'], reverse=True):
        if r['symbol'] not in best_per_sym:
            best_per_sym[r['symbol']] = r
    best_sym_list = sorted(best_per_sym.values(), key=lambda x: x['dde_v5'], reverse=True)

    # --- ALL rows sorted by score ---
    all_sorted = sorted(scored, key=lambda x: x['dde_v5'], reverse=True) + \
                 sorted(red, key=lambda x: x['dde_v5'], reverse=True)

    # ── Table header ──
    thead_html = '''<thead><tr>
<th data-col="idx" data-type="num">#<span class="arrow"></span></th>
<th data-col="signal" data-type="num">Signal<span class="arrow"></span></th>
<th data-col="ea" data-type="str">EA<span class="arrow"></span></th>
<th data-col="symbol" data-type="str">CCY<span class="arrow"></span></th>
<th data-col="dde" data-type="num"><span class="tooltip" data-tip="DDE v5 排名制分數">DDE v5</span><span class="arrow"></span></th>
<th data-col="wr" data-type="num"><span class="tooltip" data-tip="Win Rate — 真實勝率 (15%)">WR%</span><span class="arrow"></span></th>
<th data-col="pf" data-type="num"><span class="tooltip" data-tip="Profit Factor — 平均盈利/平均MAX LOSE (20%)">PF</span><span class="arrow"></span></th>
<th data-col="dd" data-type="num"><span class="tooltip" data-tip="Max Drawdown — 真實 DD (25%)">Max DD</span><span class="arrow"></span></th>
<th data-col="wal" data-type="num"><span class="tooltip" data-tip="Weighted Avg Layer — 馬丁層數 (40%)">WAL</span><span class="arrow"></span></th>
<th data-col="trades" data-type="num">Trades<span class="arrow"></span></th>
<th data-col="ht" data-type="num"><span class="tooltip" data-tip="Holding Time — 平均持倉時間（小時）">HT</span><span class="arrow"></span></th>
<th data-col="profit" data-type="num">Profit<span class="arrow"></span></th>
<th data-col="wr_pct" data-type="num"><span class="tooltip" data-tip="WR 排名百分位">WR%</span><span class="arrow"></span></th>
<th data-col="pf_pct" data-type="num"><span class="tooltip" data-tip="PF 排名百分位">PF%</span><span class="arrow"></span></th>
<th data-col="dd_pct" data-type="num"><span class="tooltip" data-tip="DD 排名百分位">DD%</span><span class="arrow"></span></th>
<th data-col="martin_pct" data-type="num"><span class="tooltip" data-tip="Martin 排名百分位">M%</span><span class="arrow"></span></th>
<th data-col="lv" data-type="str">LV<span class="arrow"></span></th>
</tr></thead>'''

    def make_row(r, idx):
        is_red = r.get('red_card', False)
        rc_cls = ' class="rc"' if is_red else ''
        ea_style = get_ea_style(r['ea'])
        sc = get_score_class(r['dde_v5'] if not is_red else 0)

        # DDE column
        if is_red:
            dde_cell = f'<td class="{sc}">0 🚫</td>'
        else:
            dde_cell = f'<td class="{sc}" data-val="{r["dde_v5"]}">{r["dde_v5"]:.1f}</td>'

        dd_cls = get_dd_class(r['max_dd_pips'])

        # Profit
        profit_cell = f'<td data-val="{r["total_net_pips"]}">{fmt_pips(r["total_net_pips"])}</td>'

        # DD
        dd_cell = f'<td class="{dd_cls}" data-val="{r["max_dd_pips"]}">{fmt_pips(r["max_dd_pips"])}</td>'

        # PF
        pf = r['pf']
        pf_str = 'Inf' if pf > 999 else f'{pf:.2f}'

        # Percentiles
        wr_pct = f'{r["wr_pct"]:.0f}'
        pf_pct = f'{r["pf_pct"]:.0f}'
        dd_pct = f'{r["dd_pct"]:.0f}'
        martin_pct = f'{r["martin_pct"]:.0f}'

        return f'''<tr data-symbol="{r['symbol']}"{rc_cls}>
<td data-val="{idx}.0">{idx}</td>
<td><a href="https://signals.algoforest.com/signals/{r['signal_id']}">{r['signal_id']}</a> <a href="../detailed_comparison_all_levels_{r['signal_id']}.html">📊</a></td>
<td><span style="{ea_style};padding:1px 6px;border-radius:3px;font-size:0.8em;font-weight:bold">{r['ea']}</span></td>
<td style="font-weight:bold;color:var(--primary)">{r['symbol']}</td>
{dde_cell}
<td data-val="{r["win_rate"]}">{r["win_rate"]:.1f}%</td>
<td data-val="{pf}">{pf_str}</td>
{dd_cell}
<td data-val="{r["wal"]}">{r["wal"]:.2f}</td>
<td data-val="{r["trades"]}">{r["trades"]:,}</td>
<td data-val="{r.get("avg_hold", 0):.1f}">{r.get("avg_hold", 0):.1f}h</td>
{profit_cell}
<td data-val="{r["wr_pct"]}">{wr_pct}</td>
<td data-val="{r["pf_pct"]}">{pf_pct}</td>
<td data-val="{r["dd_pct"]}">{dd_pct}</td>
<td data-val="{r["martin_pct"]}">{martin_pct}</td>
<td>{r['lv']}</td>
</tr>
'''

    def make_rows(rows):
        return ''.join(make_row(r, i) for i, r in enumerate(rows, 1))

    sym_options = '<option value="">All Symbols (' + str(len(sorted_syms)) + ')</option>\n'
    sym_options += '\n'.join(
        f'<option value="{sym}">{sym} ({cnt})</option>'
        for sym, cnt in sorted_syms
    )

    html = f'''<!DOCTYPE html>
<html lang="zh-HK">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>💱 CCY 排名 (v5)</title>
<style>
:root{{--font-main:-apple-system,BlinkMacSystemFont,'Segoe UI','PingFang TC','Microsoft JhengHei',sans-serif;--radius:8px;--shadow:0 2px 8px rgba(0,0,0,0.12)}}
[data-theme="dark"]{{--bg:#0a0e17;--bg-card:#111520;--bg-hover:#1a1f2e;--text:#d0d0d0;--text2:#888;--primary:#FFD700;--accent:#64b5f6;--green:#4CAF50;--red:#FF5722;--yellow:#FFC107;--orange:#fd7e14;--border:#1e2433;--th-bg:#111520;--nav-bg:transparent}}
[data-theme="light"]{{--bg:#f5f7fa;--bg-card:#ffffff;--bg-hover:#eef2f7;--text:#333;--text2:#666;--primary:#0f3460;--accent:#e94560;--green:#28a745;--red:#dc3545;--yellow:#ffc107;--orange:#fd7e14;--border:#ddd;--th-bg:#eef2f7;--nav-bg:rgba(0,0,0,0.03)}}
*{{transition:background-color .25s ease,color .25s ease,border-color .25s ease}}
.theme-toggle{{width:36px;height:36px;border:1px solid var(--border);border-radius:50%;background:var(--bg-card);color:var(--text);font-size:18px;cursor:pointer;display:flex;align-items:center;justify-content:center;box-shadow:var(--shadow);line-height:1;padding:0;flex-shrink:0}}.theme-toggle:hover{{background:var(--bg-hover);transform:scale(1.1)}}
.topnav{{display:flex;align-items:center;gap:12px;padding:10px 16px;background:var(--bg-card);border-bottom:1px solid var(--border);margin-bottom:16px;position:sticky;top:0;z-index:100}}
.topnav-logo{{font-weight:700;font-size:1em;color:var(--primary);text-decoration:none;margin-right:auto}}
.topnav-links{{display:flex;gap:10px;flex-wrap:wrap}}
.topnav-link{{color:var(--text2);text-decoration:none;font-size:.88em;font-weight:600;padding:4px 10px;border-radius:6px;transition:all .2s}}
.topnav-link:hover{{color:var(--primary);background:var(--bg-hover)}}
.topnav-link.active{{color:var(--primary);background:var(--bg-hover)}}
*{{margin:0;padding:0;box-sizing:border-box}}
body{{font-family:var(--font-main);background:var(--bg);color:var(--text);padding:16px;max-width:1400px;margin:0 auto}}
h1{{font-size:1.3em;margin-bottom:4px;color:var(--primary)}}
.sub{{color:var(--text2);font-size:0.85em;margin-bottom:16px}}
.stats{{background:var(--bg-card);border:1px solid var(--border);border-radius:8px;padding:12px 18px;margin-bottom:16px;display:flex;gap:30px;flex-wrap:wrap}}
.stats .v{{font-size:1.5em;font-weight:bold;color:var(--primary)}}
.stats .l{{font-size:0.75em;color:var(--text2)}}
select{{background:var(--bg-card);border:1px solid var(--border);color:var(--text);padding:8px 12px;border-radius:6px;margin-bottom:12px;font-size:14px}}
table{{width:100%;border-collapse:collapse;min-width:700px}}
th{{background:var(--th-bg);padding:8px 10px;text-align:left;border-bottom:2px solid var(--primary);color:var(--primary);font-size:0.8em;white-space:nowrap;cursor:pointer;user-select:none}}
th:hover{{background:var(--bg-hover)}}
th .arrow{{font-size:0.65em;margin-left:3px;opacity:0.3}}
th.asc .arrow{{opacity:1}}
th.desc .arrow{{opacity:1}}
td{{padding:6px 10px;border-bottom:1px solid var(--border);font-size:0.9em}}
tr:hover{{background:var(--bg-card)}}
tr.rc{{opacity:0.4}}
a{{color:var(--accent);text-decoration:none;font-weight:bold}}
a:hover{{text-decoration:underline}}
.container{{overflow-x:auto}}
label{{color:var(--text2);font-size:0.9em;margin-left:12px}}
input[type=text]{{background:var(--bg-card);border:1px solid var(--border);color:var(--text);padding:8px 12px;border-radius:6px;font-size:14px;width:160px}}
input[type=text]::placeholder{{color:#555}}
.s90{{color:var(--green);font-weight:bold}}.s80{{color:#8BC34A;font-weight:bold}}.s70{{color:var(--yellow);font-weight:bold}}.s60{{color:var(--orange);font-weight:bold}}.s0{{color:var(--red);font-weight:bold}}
.dd-g{{color:var(--green)}}.dd-y{{color:var(--yellow)}}.dd-r{{color:var(--red)}}
.hideRC{{display:none}}
.tabs{{display:flex;gap:0;margin-bottom:0}}
.tab{{padding:10px 20px;background:var(--bg-card);border:1px solid var(--border);color:var(--text2);cursor:pointer;border-radius:8px 8px 0 0;font-size:0.95em}}
.tab.active{{background:var(--bg);color:var(--primary);border-bottom-color:var(--bg);font-weight:bold}}
.tab:hover{{color:var(--text)}}
.panel{{background:var(--bg);border:1px solid var(--border);border-top:none;border-radius:0 0 8px 8px;padding:16px}}
.panel.hidden{{display:none}}
.tooltip{{position:relative;cursor:help}}
.tooltip::after{{content:attr(data-tip);position:absolute;bottom:120%;left:50%;transform:translateX(-50%);background:var(--bg-hover);border:1px solid #333;color:#ddd;font-size:0.75em;padding:6px 10px;border-radius:6px;white-space:nowrap;opacity:0;pointer-events:none;transition:opacity 0.2s;z-index:99;font-weight:normal}}
.tooltip:hover::after{{opacity:1}}
@media(max-width:768px){{body{{padding:8px;font-size:12px}}.tab{{padding:8px 12px;font-size:0.85em}}}}
</style>
<script>
(function(){{
  const saved=localStorage.getItem('tsa-theme');
  const t=saved||'dark';
  document.documentElement.setAttribute('data-theme',t);
  document.addEventListener('DOMContentLoaded',function(){{
    const btn=document.getElementById('theme-toggle');
    if(btn)btn.textContent=t==='dark'?'☀️':'🌙';
  }});
}})();
function toggleTheme(){{
  const cur=document.documentElement.getAttribute('data-theme');
  const next=cur==='dark'?'light':'dark';
  document.documentElement.setAttribute('data-theme',next);
  localStorage.setItem('tsa-theme',next);
  const btn=document.getElementById('theme-toggle');
  if(btn)btn.textContent=next==='dark'?'☀️':'🌙';
}}
</script>
</head>
<body>
<div class="topnav">
<a href="../index.html" class="topnav-logo">🦀 TSA</a>
<div class="topnav-links">
<a href="../signal_ranking.html" class="topnav-link">🏆 Signal 排名</a><a href="./ccy_ranking.html" class="topnav-link active">💱 CCY 排名</a><a href="./symbol_ranking.html" class="topnav-link">📊 波幅波</a>
</div>
<button class="theme-toggle" id="theme-toggle" onclick="toggleTheme()" title="切換亮/暗模式"></button>
</div>

<h1>💱 CCY 排名</h1>
<div style="display:flex;align-items:center;gap:8px;margin-bottom:12px;font-size:0.82em;color:var(--text2)">
<span>{today} · DDE v5 排名制</span>
<span style="margin-left:4px;color:var(--text2)">WR 15% + PF 20% + DD 25% + Martin 40%</span>
</div>

<div class="stats">
<div><div class="v">{len(all_results)}</div><div class="l">Total</div></div>
<div><div class="v">{n_scored}</div><div class="l">Scored</div></div>
<div><div class="v">{n_ccy}</div><div class="l">CCY</div></div>
<div><div class="v">{global_best}</div><div class="l">最高分</div></div>
<div><div class="v">{fmt_pips(total_pips)}</div><div class="l">Total P&L</div></div>
</div>

<div class="tabs">
<div class="tab active" onclick="showPanel('top20',this)">🏆 TOP 20</div>
<div class="tab" onclick="showPanel('bestsym',this)">💱 各 CCY 最佳</div>
<div class="tab" onclick="showPanel('all',this)">📋 全部明細</div>
</div>

<!-- TOP 20 -->
<div id="panel-top20" class="panel">
<h2 style="color:var(--primary);font-size:1em;margin:0 0 12px">🏆 DDE v5 總排名 Top 20</h2>
<div class="container"><table id="tbl-top20">{thead_html}<tbody>
{make_rows(top20)}
</tbody></table></div></div>

<!-- BEST PER SYMBOL -->
<div id="panel-bestsym" class="panel hidden">
<h2 style="color:var(--primary);font-size:1em;margin:0 0 12px">💱 每個 CCY 最高分的 Signal</h2>
<div class="container"><table id="tbl-bestsym">{thead_html}<tbody>
{make_rows(best_sym_list)}
</tbody></table>
<p style="color:var(--text2);font-size:0.8em;margin-top:8px">{n_ccy} 個 CCY，每個只顯示最佳 Signal</p>
</div></div>

<!-- ALL DETAIL -->
<div id="panel-all" class="panel hidden">
<h2 style="color:var(--primary);font-size:1em;margin:0 0 12px">📋 全部明細</h2>
<select id="symSel" onchange="filterSymbol()">{sym_options}</select>
<label><input type="checkbox" id="hideRC" onchange="applyFilters()"> 隱藏紅牌</label>
<span style="margin-left:12px"><input type="text" id="eaSel" placeholder="篩選 EA..." oninput="applyFilters()"> <input type="text" id="sigSel" placeholder="Signal ID..." oninput="applyFilters()"></span>
<span style="color:var(--text2);font-size:0.8em;margin-left:8px" id="rowCount"></span>
<div class="container">
<table id="tbl">{thead_html}<tbody>
{make_rows(all_sorted)}
</tbody></table></div>
</div>

<script>
function showPanel(id,el){{
  document.querySelectorAll('.panel').forEach(function(p){{p.classList.add('hidden')}});
  document.querySelectorAll('.tab').forEach(function(t){{t.classList.remove('active')}});
  document.getElementById('panel-'+id).classList.remove('hidden');
  el.classList.add('active');
}}

function getCellValue(row,colIdx,type){{
  var cell=row.cells[colIdx];if(!cell)return type==='num'?0:'';
  var dv=cell.getAttribute('data-val');
  if(dv!==null)return type==='num'?parseFloat(dv):dv;
  var text=cell.textContent.trim().replace(/[^0-9.\\-]/g,'');
  return type==='num'?(parseFloat(text)||0):cell.textContent.trim();
}}

function sortTable(table,colIdx,type){{
  var tbody=table.tBodies[0];
  var rows=Array.from(tbody.querySelectorAll('tr'));
  var ths=table.querySelectorAll('thead th');
  var dir=ths[colIdx].classList.contains('asc')?'desc':'asc';
  ths.forEach(function(h){{h.classList.remove('asc','desc')}});
  ths[colIdx].classList.add(dir);
  rows.sort(function(a,b){{
    var va=getCellValue(a,colIdx,type);
    var vb=getCellValue(b,colIdx,type);
    if(type==='num')return dir==='asc'?va-vb:vb-va;
    return dir==='asc'?String(va).localeCompare(String(vb)):String(vb).localeCompare(String(va));
  }});
  rows.forEach(function(r){{tbody.appendChild(r)}});
}}

document.querySelectorAll('table[id^="tbl"]').forEach(function(table){{
  table.querySelectorAll('thead th').forEach(function(th,i){{
    th.addEventListener('click',function(){{sortTable(table,i,th.getAttribute('data-type')||'str')}});
  }});
}});

function applyFilters(){{
  var sym=document.getElementById('symSel').value;
  var hideRC=document.getElementById('hideRC').checked;
  var eaF=document.getElementById('eaSel').value.trim().toUpperCase();
  var sigF=document.getElementById('sigSel').value.trim();
  var rows=document.querySelectorAll('#tbl tbody tr');
  var vis=0;
  rows.forEach(function(r){{
    var show=true;
    if(sym&&r.dataset.symbol!==sym)show=false;
    if(hideRC&&r.classList.contains('rc'))show=false;
    if(show&&eaF){{var ea=r.cells[2];if(!ea||ea.textContent.toUpperCase().indexOf(eaF)===-1)show=false;}}
    if(show&&sigF){{var sig=r.cells[1];if(!sig||sig.textContent.indexOf(sigF)===-1)show=false;}}
    r.style.display=show?'':'none';
    if(show)vis++;
  }});
  document.getElementById('rowCount').textContent='顯示 '+vis+' / '+rows.length;
}}
function filterSymbol(){{applyFilters();}}
var total=document.querySelectorAll('#tbl tbody tr').length;
document.getElementById('rowCount').textContent='顯示 '+total+' / '+total;
</script>
</body></html>'''

    return html


def main():
    # Try loading from pickle first
    pkl_path = '/tmp/dde_v5_data.pkl'
    if Path(pkl_path).exists():
        with open(pkl_path, 'rb') as f:
            all_results = pickle.load(f)
        print(f"📦 Loaded {len(all_results)} rows from pickle")
    else:
        # Run scoring
        from dde_v5_scorer import run_v5_scoring
        all_results = run_v5_scoring()

    html = generate_html(all_results)

    # Write to output/, reports/, and docs/
    for out_dir in [OUTPUT_DIR, REPORTS_DIR, DOCS_DIR / 'admin']:
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / 'ccy_ranking.html'
        with open(out_path, 'w', encoding='utf-8') as f:
            f.write(html)
        print(f"✅ Written: {out_path}")

    print(f"   Total rows: {len(all_results)}")
    print(f"   Size: {len(html):,} bytes")


if __name__ == '__main__':
    main()
